# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-29 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenspacesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('auto_send', models.BooleanField()),
                ('default_send_interval', models.IntegerField(default=15)),
                ('ignore_users', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.CharField(default='', max_length=256)),
                ('tweet', models.CharField(max_length=255)),
                ('original_tweet', models.CharField(max_length=255)),
                ('screen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.IntegerField(choices=[(0, 'Needs_action'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('time_interval', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('task_scheduled', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_obj', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='openspaces.OpenspacesEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('screen_name', models.CharField(blank=True, max_length=256, null=True)),
                ('should_ignore', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='streamedtweet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='openspaces.User'),
        ),
    ]
