# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtweet',
            name='tweet_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
