# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-24 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openspaces', '0002_outgoingtweet_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtweet',
            name='event_obj',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='openspaces.OpenspacesEvent'),
        ),
    ]
