# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 22:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('auto_send', models.BooleanField()),
                ('default_send_interval', models.IntegerField(default=15)),
                ('ignore_users', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
            ],
            options={
                'db_table': 'openchat_outgoingconfig',
            },
        ),
        migrations.CreateModel(
            name='OutgoingTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tweet', models.CharField(max_length=255)),
                ('approved', models.IntegerField(choices=[(0, 'Needs_action'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('time_interval', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('task_scheduled', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'openchat_outgoingtweet',
            },
        ),
        migrations.CreateModel(
            name='RetweetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'openchat_retweetevent',
            },
        ),
        migrations.CreateModel(
            name='StreamedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('favorite_count', models.IntegerField(default=-1, null=True)),
            ],
            options={
                'db_table': 'openchat_streamedtweet',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('screen_name', models.CharField(blank=True, max_length=256, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=256, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('protected', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('lang', models.CharField(blank=True, max_length=256, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('statuses_count', models.IntegerField(blank=True, null=True)),
                ('friends_count', models.IntegerField(blank=True, null=True)),
                ('favourites_count', models.IntegerField(default=-1, null=True)),
            ],
            options={
                'db_table': 'openchat_user',
            },
        ),
        migrations.AddField(
            model_name='streamedtweet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twote.User'),
        ),
    ]
