# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamedtweet',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='streamedtweet',
            name='location',
        ),
    ]
